services:

  api:
    build: .
    container_name: vector-api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env

  vector-db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_DB: vectors
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - vector_data:/var/lib/postgresql/data

volumes:
  vector_data: