name: Deploy Python API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build & Push Python API
        run: |
          docker build -t vector-api:latest ./python
          docker tag vector-api:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/vector-api:latest
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/vector-api:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_PY }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}

            cd /home/ec2-user/vector-app

            git fetch origin
            git checkout main
            git pull origin main

            docker network create common-net || true

            aws ecr get-login-password --region ap-south-1 | \
            docker login --username AWS --password-stdin \
            ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com

            docker compose pull
            docker compose down
            docker compose up -d
            docker image prune -f